[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@ensdomains/=contracts/lib/v4-core/node_modules/@ensdomains/",
    "@openzeppelin/=contracts/lib/v4-core/lib/openzeppelin-contracts/",
    "ds-test/=contracts/lib/forge-std/lib/ds-test/src/",
    "forge-gas-snapshot/=contracts/lib/v4-core/lib/forge-gas-snapshot/src/",
    "forge-std/=contracts/lib/forge-std/src/",
    "hardhat/=contracts/lib/v4-core/node_modules/hardhat/",
    "openzeppelin-contracts/=contracts/lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "solmate/=contracts/lib/v4-core/lib/solmate/src/",
    "@uniswap/v4-core/=contracts/lib/v4-core/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
